# Generated by Django 4.2.25 on 2026-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='medium',
            field=models.CharField(blank=True, help_text='Optional. Artistic medium (e.g., Oil, Acrylic, Collage)', max_length=200, verbose_name='Medium'),
        ),
        migrations.AddField(
            model_name='artist',
            name='style',
            field=models.CharField(blank=True, help_text='Optional. Artistic style (e.g., Figurative, Contemporary)', max_length=200, verbose_name='Style'),
        ),
        migrations.AddField(
            model_name='artist',
            name='theme',
            field=models.CharField(blank=True, help_text='Optional. Artistic themes (e.g., Identity, Urban Life)', max_length=200, verbose_name='Theme'),
        ),
    ]
