# Generated by Django 4.2.25 on 2026-01-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Required. Enter the artist's first name.", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text="Optional. Enter the artist's last name.", max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Specialty/Art Style')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='artists/profile_pictures/', verbose_name='Profile Picture')),
                ('image_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
