# Generated by Django 4.2.25 on 2026-02-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artist_medium_artist_style_artist_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required. Enter the artwork title.', max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('medium', models.CharField(blank=True, help_text='Optional. e.g., Oil on canvas, Bronze sculpture', max_length=200, verbose_name='Medium')),
                ('dimensions', models.CharField(blank=True, help_text='Optional. e.g., 120 × 100 cm', max_length=100, verbose_name='Dimensions')),
                ('year', models.IntegerField(help_text='Required. Year the artwork was created.', verbose_name='Year')),
                ('status', models.CharField(choices=[('available', 'Available'), ('at_gallery', 'Available at Gallery'), ('on_request', 'Available on Request'), ('sold', 'Sold')], default='available', max_length=20, verbose_name='Status')),
                ('show_price', models.BooleanField(default=True, help_text='Display price on website', verbose_name='Show Price')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in Rands', max_digits=10, null=True, verbose_name='Price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Discounted price if on sale', max_digits=10, null=True, verbose_name='Discounted Price')),
                ('allow_purchase', models.BooleanField(default=True, help_text='Allow customers to purchase this artwork online', verbose_name='Allow Purchase')),
                ('allow_inquiry', models.BooleanField(default=True, help_text='Allow customers to inquire about this artwork', verbose_name='Allow Inquiry')),
                ('allow_schedule_viewing', models.BooleanField(default=True, help_text='Allow customers to schedule a viewing', verbose_name='Allow Schedule Viewing')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/', verbose_name='Artwork Image')),
                ('image_url', models.URLField(blank=True, help_text='Alternative image URL if not uploaded', verbose_name='Image URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='gallery.artist', verbose_name='Artist')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-created_at'],
            },
        ),
    ]
