# Generated by Django 4.2.25 on 2026-02-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
