# Generated by Django 4.2.25 on 2026-02-03 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_delete_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required. Enter the title of the artwork.', max_length=200, verbose_name='Artwork Title')),
                ('availability', models.CharField(choices=[('at_gallery', 'Available at Gallery'), ('available', 'Available'), ('on_request', 'Available on Request')], default='available', help_text='How this artwork can be acquired by customers.', max_length=20, verbose_name='Availability Status')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Required unless "Available on Request". Enter price in local currency.', max_digits=10, null=True, verbose_name='Price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Special promotional price.', max_digits=10, null=True, verbose_name='Discounted Price')),
                ('sold', models.BooleanField(default=False, help_text='Mark as sold if this artwork has been purchased.', verbose_name='Sold')),
                ('medium', models.CharField(blank=True, help_text='Optional. Artistic medium (e.g., Oil on Canvas, Bronze Sculpture)', max_length=200, verbose_name='Medium')),
                ('dimensions', models.CharField(blank=True, help_text='Optional. Artwork dimensions (e.g., 120 × 100 cm)', max_length=100, verbose_name='Dimensions')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Optional. Year the artwork was created.', null=True, verbose_name='Year')),
                ('description', models.TextField(blank=True, help_text='Optional. Detailed description of the artwork.', verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/images/', verbose_name='Artwork Image')),
                ('image_url', models.URLField(blank=True, help_text='Optional. URL to artwork image if hosted elsewhere.', verbose_name='Image URL')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this artwork from the website.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(help_text='Required. Select the artist who created this artwork.', on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='gallery.artist', verbose_name='Artist')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artist', 'is_active', 'sold'], name='gallery_art_artist__fd0b91_idx'), models.Index(fields=['availability', 'is_active'], name='gallery_art_availab_e0cc14_idx'), models.Index(fields=['price'], name='gallery_art_price_8682ab_idx')],
            },
        ),
    ]
